server:
  port: 9001

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:user-service-db;DB_CLOSE_DELAY=-1;
    username: admin
    password: 123qwe
    driver-class-name: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

user-service:
  ribbon:
    listOfServers: http://localhost:9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  security:
    enabled: false

endpoints.enabled: false

endpoints:
  info.enabled: true
  health.enabled: true