server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
              
zuul:
  routes:
    users:
      path: /users/**
      url: http://localhost:9001

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

jwt:
  secret: jwt-sample-secret

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 70000
        forceClosed: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  shareSecurityContext: true