server:
  port: 9004

spring:
  application:
    name: location-provider-service
  kafka:
    bootstrap-servers: localhost:29092
  data:
    elasticsearch:
      cluster-name: es-cluster
      cluster-nodes: localhost:9300
  elasticsearch:
    rest:
      uris: http://localhost:9200