spring:
  profiles:
    active: native
  application:
    name: zuul-gateway-service
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  cloud:
    config:
      uri: http://localhost:8888
      retry:
        initialInterval: 10000
        multiplier: 1.3
        maxInterval: 5000
        maxAttempts: 10
      fail-fast: true

sample:
  variable: Sample var on Native profile